#!/usr/bin/env bash

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/gu" install native-image || true

# if one wants to use :sci
# lein with-profiles +sci,+clojure-1.10.2-alpha1 do clean, uberjar

lein with-profiles +clojure-1.10.2-alpha1 do clean, uberjar

args=( "-jar" "target/woop-0.0.1-standalone.jar" \
              "-H:CLibraryPath=libs" \
              "-H:Name=woop" \
              "-H:+ReportExceptionStackTraces" \
              "-J-Dclojure.spec.skip-macros=true" \
              "-J-Dclojure.compiler.direct-linking=true" \
              "--initialize-at-build-time"  \
              "-H:ReflectionConfigurationFiles=reflection.json"
              "-H:Log=registerResource:" \
              "--verbose" \
              "--no-fallback" \
              "--no-server" \
              "--report-unsupported-elements-at-runtime"
              # "-J-Xmx3g"
     )

$GRAALVM_HOME/bin/native-image "${args[@]}"
